lib/tasktracker_web/router.ex
defmodule TasktrackerWeb.Router do
  use TasktrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :get_current_user
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Below the pipeline
  def get_current_user(conn, _params) do
    # TODO: Move this function out of the router module.
    user_id = get_session(conn, :user_id)
    user = Tasktracker.Accounts.get_user(user_id || -1)
    assign(conn, :current_user, user)
  end

  scope "/", TasktrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/feed", PageController, :feed
    get "/managee_feed", PageController, :managee_feed
    get "/profile", PageController, :profile
    resources "/users", UserController
    resources "/tasks", TaskController
    post "/session", SessionController, :create
    delete "/session",SessionController, :delete
    delete "/timeblocks/:id", TimeblockController, :delete
  end

  scope "/api/v1", TasktrackerWeb do
    pipe_through :api
    resources "/manages", ManageController, except: [:new, :edit]
    resources "/timeblocks", TimeblockController, except: [:new, :edit]
  end


  # Other scopes may use custom stacks.
  # scope "/api", TasktrackerWeb do
  #   pipe_through :api
  # end
end

lib/tasktracker_web/templates/page/feed.html.eex
<h1>Your Task Feed</h1>
<%= if Enum.count(@tasks) == 0 do %>
<p> Tasks assigned to you will show up in this place </p>
<% else %>
<%= if @tasks do %>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Completed</th>
      <th>Time Spent
      (Minutes)</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for task <- @tasks do %>
    <tr>
      <td><%= task.title %></td>
      <td><%= task.description %></td>
      <td>
      <%= if task.completed do %>
        Yes
      <% end %>
      <%= if !task.completed do %>
         No
      <% end %>
      </td>
      <td><%= List.foldl( task.timeblocks,0 ,fn(x, acc) -> acc + DateTime.diff(x.endtime, x.starttime) end)
      |> div(60) %></td>
      <td><%= if !task.completed && task.user_id == @current_user.id do %>
      <button class="time-block" data-start-time="" data-task-id="<%= task.id%>" data-user-id="<%= @current_user.id %>">Start Working</button><%end%></td>
        <td class="text-right">
        <%= link "Show", to: task_path(@conn, :show, task), class: "btn btn-default btn-xs" %>
        <%= if !task.completed && task.user_id == @current_user.id do %>
        <%= link "Edit", to: task_path(@conn, :edit, task), class: "btn btn-default btn-xs" %>
        <% end %>
        <%= link "Delete", to: task_path(@conn, :delete, task), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>
<% end %>
<% end %>

lib/tasktracker_web/templates/page/index.html.eex
<h1>Welcome to Task tracking app</h1>
    <!-- session_path(@conn, :create) -->
    <%= if @current_user do  %>
    <div>You are logged in.</div>
    <p><%= link "Task Page", to: page_path(@conn, :feed, user_id: @current_user.id) %></p>
    <%= if @current_user.manager do  %>
    <p><%= link "Managee Task Page", to: page_path(@conn, :managee_feed, user_id: @current_user.id) %></p>
    <% end %>
    <% else %>
    <h1>Log In</h1>
    <%= form_tag("/session", method: :post) do %>
      <div class="form-group">
        Email
        <input type="email" name="email" placeholder="user@example.com" >
      </div>
      <!-- passwords come later -->
      <div class="form-group">
        <button class="btn btn-primary">Log in</button>
        <%= link "Register", to: user_path(@conn, :new) %>
      </div>
    <% end %>
    <% end %>

lib/tasktracker_web/templates/page/managee_feed.html.eex
<h1>Managees Task Feed</h1>
<%= if Enum.count(@tasks) == 0 do %>
<p> Tasks assigned to your managees will show up in this place </p>
<p>Create a new task? <%= link "New Task" ,to: task_path(@conn, :new) %></p>
<% else %>
<p>Create a new task? <%= link "New Task" ,to: task_path(@conn, :new) %></p>
<%= if @tasks do %>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Assigned To</th>
      <th>Completed</th>
      <th>Time Spent
         (Minutes)
      </th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for task <- @tasks do %>
    <tr>
      <td><%= task.title %></td>
      <td><%= task.description %></td>
      <td><%= task.user.name %></td>
      <td>
      <%= if task.completed do %>
        Yes
      <% else %>
         No
      <% end %>
      </td>
      <td><%= List.foldl(task.timeblocks,0 ,fn(x, acc) -> acc + DateTime.diff(x.endtime, x.starttime) end)
            |> div(60) %></td>
      <td></td>
        <td class="text-right">
        <%= link "Show", to: task_path(@conn, :show, task), class: "pull-right btn btn-default btn-xs" %>
        <%= if !task.completed do %>
        <%= link "Edit", to: task_path(@conn, :edit, task), class: "pull-right btn btn-default btn-xs" %>
        <% end %>
        <%= link "Delete", to: task_path(@conn, :delete, task), method: :delete, data: [confirm: "Are you sure?"], class: "pull-right btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>
<% end %>
<% end %>

lib/tasktracker_web/templates/page/profile.html.eex
<script>
 window.manage_path = "<%= manage_path(@conn, :index) %>";
 window.current_user_id = "<%= @current_user.id %>";
</script>
<div>
<p>Welcome to your profile page: <%= @current_user.name %></p>
<p><%=if @manager != "" do %>
Your manager is <%= @manager.name %>
<% end %></p>
<p>Visit your task page: <%= link "Task Page", to: page_path(@conn, :feed, user_id: @current_user.id) %></p>
<%= if @current_user.manager do %>
<p>Visit your managee task page: <%= link "Managee Task Page", to: page_path(@conn, :managee_feed, user_id: @current_user.id) %></p>
<p>Create a new task? <%= link "New Task" ,to: task_path(@conn, :new) %></p>
<div>
<h2>Listing Users</h2>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.name %></td>
      <td><%= user.email %></td>

      <td class="text-right">
              <button class="manage-button btn btn-default"
                      data-user-id="<%= user.id %>"
                      data-manage="<%= @manages[user.id] %>">
                Manage
              </button>
      </td>
    </tr>
<% end %>
  </tbody>
</table>
<% end %>
</div>
</div>