lib/tasktracker_web/router.ex
defmodule TasktrackerWeb.Router do
  use TasktrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :get_current_user
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  # Below the pipeline
  def get_current_user(conn, _params) do
    # TODO: Move this function out of the router module.
    user_id = get_session(conn, :user_id)
    user = Tasktracker.Accounts.get_user(user_id || -1)
    assign(conn, :current_user, user)
  end

  scope "/", TasktrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/feed", PageController, :feed
    get "/managee_feed", PageController, :managee_feed
    get "/profile", PageController, :profile
    resources "/users", UserController
    resources "/tasks", TaskController
    post "/session", SessionController, :create
    delete "/session",SessionController, :delete
    delete "/timeblocks/:id", TimeblockController, :delete
  end

  scope "/api/v1", TasktrackerWeb do
    pipe_through :api
    resources "/manages", ManageController, except: [:new, :edit]
    resources "/timeblocks", TimeblockController, except: [:new, :edit]
  end


  # Other scopes may use custom stacks.
  # scope "/api", TasktrackerWeb do
  #   pipe_through :api
  # end
end

lib/tasktracker/task_manager/task.ex
defmodule Tasktracker.TaskManager.Task do
  use Ecto.Schema
  import Ecto.Changeset
  alias Tasktracker.TaskManager.Task

  schema "tasks" do
    field :completed, :boolean, default: false
    field :description, :string
    field :title, :string
    belongs_to :user, Tasktracker.Accounts.User
    has_many :timeblocks, Tasktracker.TaskManager.Timeblock
    timestamps()
  end

  @doc false
  def changeset(%Task{} = task, attrs) do
    task
    |> cast(attrs, [:title, :description, :completed, :user_id])
    |> validate_required([:title, :description, :completed, :user_id])
    |> cast_assoc(:timeblocks)
  end

end

lib/tasktracker_web/controllers/task_controller.ex
defmodule TasktrackerWeb.TaskController do
  use TasktrackerWeb, :controller

  alias Tasktracker.TaskManager
  alias Tasktracker.TaskManager.Task
  alias Tasktracker.Repo

  def new(conn, _params) do
    task = %Task{}
    changeset = TaskManager.change_task(task)
    current_user = conn.assigns[:current_user]
    users = Tasktracker.Accounts.list_users_for_task_assignment(current_user.id)
            |> Enum.map(&{&1.name, &1.id})
    render(conn, "new.html", changeset: changeset, users: users)
  end

  def create(conn, %{"task" => task_params}) do
    current_user = conn.assigns[:current_user]
    case TaskManager.create_task(task_params) do
      {:ok, task} ->
        conn
        |> put_flash(:info, "Task created successfully.")

        ## If the manager creates a task for himself,
        ## Go to this task feed, else go to the managee feed
        if task.user_id == current_user.id do
          conn
          |> redirect(to: page_path(conn, :feed, user_id: get_session(conn, :user_id)))
        else
          conn
          |> redirect(to: page_path(conn, :managee_feed, user_id: get_session(conn, :user_id)))
        end

      {:error, %Ecto.Changeset{} = changeset} ->
        users = users = Tasktracker.Accounts.list_users_for_task_assignment(current_user.id)
                        |> Enum.map(&{&1.name, &1.id})
        render(conn, "new.html", changeset: changeset, users: users)
    end
  end

  def show(conn, %{"id" => id}) do
    current_user = conn.assigns[:current_user]
    case current_user.manager do
      true ->
        task = TaskManager.get_task_with_time_blocks_managee!(id, current_user.id)
        render(conn, "show.html", task: task)
      false ->
        task = TaskManager.get_task_with_time_blocks!(id, current_user.id)
        render(conn, "show.html", task: task)
    end
  end


  def edit(conn, %{"id" => id}) do
    current_user = conn.assigns[:current_user]
    task = TaskManager.get_task_with_time_blocks!(id, get_session(conn, :user_id))
    changeset = TaskManager.change_task(task)
    users = Tasktracker.Accounts.list_users_for_task_assignment(current_user.id)
            |> Enum.map(&{&1.name, &1.id})
    render(conn, "edit.html", task: task, changeset: changeset, users: users)
  end

  def update(conn, %{"id" => id, "task" => task_params}) do
    current_user = conn.assigns[:current_user]
    task = TaskManager.get_task_with_time_blocks!(id, get_session(conn, :user_id))
    case TaskManager.update_task(task, task_params) do
      {:ok, task} ->
        conn = conn
        |> put_flash(:info, "Task updated successfully.")

        # similar redirection compared to new
        if task.user_id == current_user.id do
          conn
          |> redirect(to: page_path(conn, :feed, user_id: get_session(conn, :user_id)))
        else
          conn
          |> redirect(to: page_path(conn, :managee_feed, user_id: get_session(conn, :user_id)))
        end
      {:error, %Ecto.Changeset{} = changeset} ->
        users = Tasktracker.Accounts.list_users_for_task_assignment(current_user.id)
                |> Enum.map(&{&1.name, &1.id})
        render(conn, "edit.html", task: task, users: users, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    current_user = conn.assigns[:current_user]
    task = TaskManager.get_task!(id)
    {:ok, _task} = TaskManager.delete_task(task)
    conn
    |> put_flash(:info, "Task deleted successfully.")

    if task.user_id == current_user.id do
      conn
      |> redirect(to: page_path(conn, :feed, user_id: get_session(conn, :user_id)))
    else
      conn
      |> redirect(to: page_path(conn, :managee_feed, user_id: get_session(conn, :user_id)))
    end
  end
end

lib/tasktracker_web/views/task_view.ex
defmodule TasktrackerWeb.TaskView do
  use TasktrackerWeb, :view
end

lib/tasktracker_web/templates/task/edit.html.eex
<h2>Edit Task</h2>

<%= render "timeblock_form.html", Map.put(assigns, :action, task_path(@conn, :update, @task)) %>

<%= if @current_user.manager do  %>
<p>Back to: <%= link "Task Feed", to: page_path(@conn, :feed, user_id: @current_user.id) %></p>
<p>Back to: <%= link "Managee Task Feed", to: page_path(@conn, :managee_feed, user_id: @current_user.id) %></p>
<% else %>
<p>Back to: <%= link "Task Feed", to: page_path(@conn, :feed, user_id: @current_user.id) %></p>
<% end %>

lib/tasktracker_web/templates/task/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

 <div class="form-group">
   <%= label f, :user_id, "Assigned To", class: "control-label" %>
   <%= select f, :user_id, @users ,class: "form-control", id: "select-user-id" %>
 </div>

  <div class="form-group">
    <%= label f, :description, class: "control-label" %>
    <%= textarea f, :description, class: "form-control" %>
    <%= error_tag f, :description %>
  </div>

  <div class="form-group">
    <%= label f, :completed, class: "control-label" %>
    <%= checkbox f, :completed, class: "checkbox" %>
    <%= error_tag f, :completed %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/tasktracker_web/templates/task/index.html.eex
<h2>Listing Tasks</h2>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Completed</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for task <- @tasks do %>
    <tr>
      <td><%= task.title %></td>
      <td><%= task.description %></td>
      <td><%= task.completed %></td>

      <td class="text-right">
        <span><%= link "Show", to: task_path(@conn, :show, task), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: task_path(@conn, :edit, task), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: task_path(@conn, :delete, task), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Task", to: task_path(@conn, :new) %></span>
<span><%= link "Home Page", to: "/" %></span>

lib/tasktracker_web/templates/task/new.html.eex
<h2>New Task</h2>

<%= render "form.html", Map.put(assigns, :action, task_path(@conn, :create)) %>

<%= if @current_user.manager do  %>
<p>Back to: <%= link "Task Feed", to: page_path(@conn, :feed, user_id: @current_user.id) %></p>
<p>Back to: <%= link "Managee Task Feed", to: page_path(@conn, :managee_feed, user_id: @current_user.id) %></p>
<% else %>
<p>Back to: <%= link "Task Feed", to: page_path(@conn, :feed, user_id: @current_user.id) %></p>
<% end %>

lib/tasktracker_web/templates/task/show.html.eex
<h2>Show Task</h2>

<ul>
  <li>
    <strong>Title:</strong>
    <%= @task.title %>
  </li>

  <li>
    <strong>Description:</strong>
    <%= @task.description %>
  </li>

  <li>
      <strong>Assigned To:</strong>
      <%= @task.user.name %>
  </li>

  <li>
    <strong>Completed:</strong>
    <%= if @task.completed do %>
        Yes
    <% end %>
    <%= if !@task.completed do %>
        No
    <%end%>
  </li>
    <%= if Enum.count(@task.timeblocks) != 0 do %>
    <li>
      <strong>Time Blocks:</strong>
      <%= for timeblock <- @task.timeblocks do %>
      <ul>
            <li>Start Time: <%=
            Timex.local(timeblock.starttime)
            %></li>
            <li>End Time: <%= Timex.local(timeblock.endtime)%></li>
      </ul>
      <% end %>
    </li>
    <% end %>
</ul>
<p>
<%= if !@task.completed  do %>
<%= link "Edit", to: task_path(@conn, :edit, @task), class: "btn btn-default btn-xs" %>
<% end %>
</p>
<%= if @current_user.manager do  %>
<p>Back to: <%= link "Task Feed", to: page_path(@conn, :feed, user_id: @current_user.id) %></p>
<p>Back to: <%= link "Managee Task Feed", to: page_path(@conn, :managee_feed, user_id: @current_user.id) %></p>
<% else %>
<p>Back to: <%= link "Task Feed", to: page_path(@conn, :feed, user_id: @current_user.id) %></p>
<% end %>

lib/tasktracker_web/templates/task/timeblock_form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

   <%= if @current_user.id != @task.user_id do  %>
    <div class="form-group">
      <%= label f, :user_id, "Assigned To", class: "control-label" %>
      <%= select f, :user_id, @users ,class: "form-control", id: "select-user-id", disabled: !@current_user.manager %>
    </div>
   <% end %>

   <%= if @current_user.manager && @current_user.id == @task.user_id do  %>
       <div class="form-group">
         <%= label f, :user_id, "Assigned To", class: "control-label" %>
         <%= select f, :user_id, @users ,class: "form-control", id: "select-user-id", disabled: !@current_user.manager %>
       </div>
      <% end %>

   <%= if @current_user.id == @task.user_id do  %>
   <%= inputs_for f, :timeblocks, fn i -> %>
   <div class="form-group">
        <%= label i, :starttime, "Start Time: ", class: "control-label" %>
        <%= datetime_select i, :starttime %>
        <%= label i, :endtime, "End Time: ", class: "control-label" %>
        <%= datetime_select i, :endtime %>
        <div>
        <%= error_tag i, :starttime %>
        </div>
        <%= link "Delete", to: timeblock_path(@conn, :delete, i.data.id), method: :delete %>
   </div>
    <% end %>
    <% end %>

  <div class="form-group">
    <%= label f, :description, class: "control-label" %>
    <%= textarea f, :description, class: "form-control" %>
    <%= error_tag f, :description %>
  </div>

  <div class="form-group">
    <%= label f, :completed, class: "control-label" %>
    <%= checkbox f, :completed, class: "checkbox" %>
    <%= error_tag f, :completed %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>